### ISSUE TITLE
Is the logo acceptable?

### ISSUE THREAD

**Issue by cmeeren** [cmeeren/Felicity#1]
@reedcopsey Is the current project logo (see below) acceptable? It's inspired by the F# logo in the sense that it uses the same basic geometric primitives and shapes, but they are arranged differently (and mixed with elements from the [JSON:API logo](https://jsonapi.org/images/jsonapi.png)).

I am concerned about the following from [foundation.fsharp.org/logo](http://foundation.fsharp.org/logo):

> Do not alter the image shape, color, or proportions.

The logo could be seen as having "altered the shape" of the F# logo. I think it is acceptable since I am "just" inspired by the geometry and colors, but I can see that it might be contentious (e.g. look "too much" like the F# logo), so I'd just like to be on the safe side and ask sooner rather than later.

My goal is for the logo to be unique and "single" (i.e. not directly use the F# logo), yet still feel instantly familiar to the F# community. The F# logo has wonderfully simple and generic geometric primitives that can be mixed together in different ways to make this work. I think it does the job, while still being different enough from the F# logo that users won't mistake it for the actual F# logo.

If the logo is not acceptable, I'd appreciate some guidance as to how to make it acceptable.

<img src="https://raw.githubusercontent.com/cmeeren/Felicity/51395c5e2d8141e29868e0dad33b4b5ad163599a/felicity-logo.png"/>

**Comment by ReedCopsey** [comment]
I think this is acceptable. Thank you for checking.

**Comment by cmeeren** [comment]
Thanks!
