### ISSUE TITLE
Custom query parameter

### ISSUE THREAD

**Issue by MortalFlesh** [cmeeren/Felicity#3]
Hello,

I'm trying to add a custom query parameter for POST method.

## Reason/Use-case
I have a multi-tenant api, and the caller has to provide a name of his tenant - so api would know, which part of the database it should use.

## Problem
I've found this [custom-query-parameters](https://github.com/cmeeren/Felicity/blob/master/DOCUMENTATION.md#custom-query-parameters) in docs and example [here](https://github.com/cmeeren/Felicity/blob/master/DOCUMENTATION.md#custom-operationslinks)

```fs
let! someParam = parser.GetRequired(Query.Bool("someQueryParam"))
```

I've tried
```fs
let post =
        define.Operation
            .Post(fun ctx parser ->
                parser.ForAsyncRes(
                    asyncResult {
                        let! spot = parser.GetOptional(Query.ParsedOpt("spot", Some)) |> Hopac.Job.toAsync
                        printfn "Spot: %A" spot
                        // ...
```
and also `Query.String("spot")`

I also tried it in creating `jsonApiContext` to make it "globally" available, by parsing `HttpContext` directly.

But I get this error every time:
```json
{
  "errors": [
    {
      "id": "4bb6ea2bdb1d4e7cba15d9273bd2ebb2",
      "status": "400",
      "title": "Invalid query parameter name",
      "detail": "'spot' is not an allowed query parameter name according to the JSON:API specification",
      "source": {
        "parameter": "spot"
      }
    }
  ]
}
```

Should I register my custom query parameters somehow first? Is it against json-api specification?

Thanks in advance!

**Comment by cmeeren** [comment]
According to JSON:API query parameter names must contain at least one non-lowercase character. (The rules are a bit more complex, but that's the simple version.) For example, `spotId` or `Spot` would be valid, but `spot` is not, because all lowercase-only query parameter names are reserved by the JSON:API spec for future use.

**Comment by cmeeren** [comment]
By the way, in your case, if you use the string value directly, `Query.String("spot")` (with another name, of course) would be the simplest thing.

**Comment by MortalFlesh** [comment]
Hello,

I'll use `Spot` then. Thanks for explanation.

---

> By the way, in your case, if you use the string value directly, `Query.String("myParam")` would be the simplest alternative.

Yea I though so, I just tried different ways to test the scenario.
