### ISSUE TITLE
How to access HttpContext AfterCreate entity

### ISSUE THREAD

**Issue by MortalFlesh** [cmeeren/Felicity#6]
Hello, its me again :)

I'm currently adding an open tracing (Jaeger) into my applications and I'd like to add tag for my span with `http.status_code` of the response.

According to https://opentracing.io/docs/best-practices/#tracing-client-calls it should be set "on done", which IMO means "in the end of execution". Or simply, when you already know, what status_code it should be.

So I'd say in terms of json api and felicity, it should be in (_or ideally after_) `AfterCreate` body.

```fs
let post =
    define.Operation
        .Post(fun ctx parser -> ...)
        .AfterCreate(fun ctx resource ->
            ctx.Persist resource

            // now it is all done, and without tracing, it would be the end of this function
            |> tee (fun _ ->
                use activeTrace = Trace.active()
                activeTrace 
                |> Trace.addTags [
                    "http.status_code", "201"
                ]
            )
        )
```

_Note: In the example I've used a pseudo code for tracing._

Example above is the way it works and the way I have it right now.

But as I mentioned before, ideally it should be "after" `AfterCreate` because I'd rather use dynamic way to get a `status_code` than hardcoded it in.

It'd be much better like this:
```fs
activeTrace 
|> Trace.addTags [
    "http.status_code", string ctx.HttpContext.Response.StatusCode
]
```

Problem is, that the `status_code` is set to the response after the `AfterCreate` function is resolved - https://github.com/cmeeren/Felicity/blob/master/src/Felicity/Operations.fs#L363

So there is no way (AFAIK) how to get the "real" status code of the response in or after `AfterCreate` - or is it?

Thanks in advance :)

**Comment by MortalFlesh** [comment]
Hello,

just in case anyone would need to solve this, the feature from version `0.17.4` is exactly what you need!
https://github.com/cmeeren/Felicity/blob/master/DOCUMENTATION.md#apply-a-httphandler-beforeafter-the-endpoints-or-perform-other-modifications

Thank you for this 🥇

**Comment by cmeeren** [comment]
To be precise, that was always possible. I only added that because I changed to endpoint routing. Before, you could do this in your routing:

```f#
myBeforeHandler >=> jsonApi<MyContext> >=> myAfterHandler
```

After changing to ASP.NET Core's endpoint routing and removing the `jsonApi<_>` handler, this was no longer possible. Hence the modification of `UseJsonApiEndpoints` to allow you to use Giraffe's built-in functionality to achieve the same.
